name: "Bug Report"
description: Create a new ticket for a bug.
title: "[BUG] - <title>"
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true

  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: Enter the GitHub URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: false

  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Explicitly describe your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](img_link.png)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Copy any relevant log output.
      render: bash
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: What should happen instead?
      placeholder: Describe the expected result...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: "Impact"
      description: How critical is this issue?
      options:
        - Blocking 
        - Major 
        - Minor 
        - Other ? (specify in description)
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - Other ? (specify in description)
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false