name: CI Quality Check

on:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Quality Checks
        run: |
          cargo check
          cargo fmt --check
          cargo clippy

      - name: Python Format Check # Dans cette section, nous vérifions le formatage du code Python en utilisant l'outil Black. Si le code n'est pas correctement formaté, cette étape échouera et signalera un problème dans la pull request.
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
          python -m black --check .