name: PR Target Control

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  verify-target:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Close invalid PR
        if: startsWith(github.base_ref, 'release/') && github.head_ref != 'main' && !startsWith(github.head_ref, 'bug/')
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Erreur: Seules les branches main ou bug/x peuvent être fusionnées dans une branche release/x."