name: CI-QUALITY-CHECK

on:
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: make full-check

      - name: black install
        run: pip install black

      - name: python format check # fail if not formatted correctly
        run: black --check tests/