name: My Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run cargo check
        run: cargo check --verbose
